# Generated by Django 3.1.5 on 2021-02-09 13:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friend_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
