# Generated by Django 3.1.5 on 2021-03-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_chat', '0002_auto_20210209_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
