# Generated by Django 3.1.5 on 2021-02-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_chat', '0002_auto_20210206_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='phone_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='chat',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
