# Generated by Django 3.1.5 on 2021-02-08 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_chat', '0003_auto_20210208_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='phone_number',
            new_name='mobile_number',
        ),
    ]
