# Generated by Django 3.1.5 on 2021-02-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_chat', '0004_auto_20210208_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='mobile_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='chat',
            name='profile_pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
