# Generated by Django 3.1.5 on 2021-04-07 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real_chat', '0005_auto_20210323_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlist',
            name='current_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_user', to='real_chat.user'),
        ),
    ]
