# Generated by Django 3.1.5 on 2021-04-13 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_chat', '0007_hiddenfriends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hiddenfriends',
            old_name='curr_user',
            new_name='current_user',
        ),
    ]
