# Generated by Django 3.1.5 on 2021-04-13 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real_chat', '0008_auto_20210413_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiddenfriends',
            name='hiddenFriends',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hideFriend', to='real_chat.user'),
        ),
    ]
