# Generated by Django 3.1.5 on 2021-04-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_chat', '0009_hiddenfriends_hiddenfriends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiddenfriends',
            name='hiddenFriends',
        ),
    ]
